### PR TITLE
fix: ESM compatibility

### PR DESCRIPTION
**Pull request by ffMathy**
Supersedes https://github.com/ftrackhq/ftrack-javascript/pull/199

- [x] I have added automatic tests where applicable
- [x] The PR title is suitable as a release note
- [x] The PR contains a description of what has been changed
- [x] The description contains manual test instructions

### CODE REVIEW

**Comment by ffMathy** [comment]
CC @jimmycallin.

**Comment by jimmycallin** [comment]
When you tested this by changing this locally, did you rename the outputted file to `.mjs` as well or just updated the package.json?

**Comment by ffMathy** [comment]
I renamed the file as well. I also just now tried renaming it back, and then it doesn't work. So it is indeed needed.

**Comment by jimmycallin** [comment]
I'm a bit confused why this is needed for @ftrack/web-widget and not @ftrack/api so wonder if there is another underlying issue with the config that renaming to mjs hides. Will try to have a closer look later today.

**Comment by ffMathy** [comment]
I mean, either way it's good practice to use the mjs format, and I can't see a scenario where it breaks anything.

Let me know what you find either way. It's very interesting.

**Comment by jimmycallin** [comment]
@ffMathy the issue is actually a missing property `"type": "module"` in package.json, mind updating your pr and verifying that it works?

**Comment by ffMathy** [comment]
Well, now we are switching away from Jest as well and to Vitest, just like you 😆 I think we got inspired.

The VS Code Extension for Jest is a bit annoying.

So I won't have time to check this out unfortunately.

**Comment by jimmycallin** [comment]
Good choice :) I'll go ahead and close this PR and apply the fixes separately

**Pull request closed without merging**
